# Generated by Django 6.0.3 on 2026-04-06 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0003_customer_loyalty_points'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='loyalty_points',
        ),
    ]
