# Generated by Django 4.2 on 2026-04-07 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0004_remove_customer_loyalty_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='discount_percent',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Special discount % for this customer on every bill', max_digits=5),
        ),
    ]
