# Generated by Django 4.2 on 2026-05-11 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StoreSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(default='Sultan Mart', max_length=200)),
                ('store_address', models.TextField(blank=True, default='')),
                ('store_phone', models.CharField(blank=True, default='', max_length=30)),
                ('store_gst', models.CharField(blank=True, default='', max_length=20)),
                ('admin_pin', models.CharField(default='1234', max_length=10)),
                ('receipt_footer', models.CharField(default='Thank you! Visit Again.', max_length=300)),
                ('show_gst_on_receipt', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'store_settings',
            },
        ),
    ]
